[package]
name = "rlpi"
version = "0.1.0"
authors = ["lee"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2"
clap = "2.33.3"

[[bin]]
name="job_mon"
path="src/pgsjc/job_mon.rs"

[[bin]]
name="handling_sigtstp"
path="src/pgsjc/handling_sigtstp.rs"

[[bin]]
name="orphaned_pgrp_sighup"
path="src/pgsjc/orphaned_pgrp_sighup.rs"